config/routes.rb
Students::Application.routes.draw do

  root :to => "public#index"
  # new pages, behind a feature flag
  get 'new-root' => redirect('/')
  get 'people/:id' => "public#show", as: :public_student

  get 'signin' => "sessions#new", as: :signin
  post 'signin' => "sessions#sign_in_with_password"
  get 'set_password/:verifier' => "sessions#set_password", as: :set_password
  post 'set_password/:verifier' => "sessions#update_password"

  get "/preparation" => "public_pages#preparation_index", :as => "preparations"
  get "/preparation/:id" => "public_pages#preparation", :as => "preparation"
  get "/calendar" => "public_pages#calendar", :as => "calendar"
  resources :showcases
  resources :students, :only => :show

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure"
  get "/logout" => "sessions#destroy", :as => "logout"

  get "/mentors/:user_id" => "mentors#show", :as => :mentor

  resources :timelines, only: :index
  resources :campuses
  resources :courses do
    post :clone, on: :member
    resources :expectations
  end
  resources :job_activities, only: [] do
    get :all, on: :collection
  end
  resources :assessments
  resources :given_assessments, only: :create
  resources :enrollments
  resources :videos, only: :index

  resources :curriculums, only: [] do
    resources :learning_experiences do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
      get :assign, on: :collection
      post :assign, on: :member, action: :create_assignment
    end
    resources :exercises
  end

  resources :curriculums, module: :instructor do
    get :new_import, on: :member
    post :import, on: :member
    get :progress, on: :member
    get :activity, on: :member
    resources :standards, only: [:index, :new, :create] do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
    resources :subjects do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
  end
  resources :standards, module: :instructor do
    post :merge_objectives, on: :member
    get :delete, on: :member
    resources :objectives, only: [:new, :create] do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
  end
  resources :objectives, module: :instructor do
    get :delete, on: :member
  end

  namespace :api do
    get 'me' => 'base#me'
    post '/apps/:app_name/authenticate' => 'apps#authenticate'
    get 'sign-in' => 'auth#sign_in'
    resources :cohort_exercises, only: [] do
      resources :submissions, only: :index
    end
    resources :class_projects, only: :index
    resources :students, only: :index
    resources :student_projects, only: :index
    resources :stories
    resources :cohorts, only: :index do
      get :current, on: :collection
      resources :students, only: :index
    end
    get '/autograder/:cohort_id' => 'autograder#show'
  end

  get '/redirects/learning_experiences/:id' => 'redirects#learning_experience'

  resources :users do
    resources :performances, controller: 'users/performances' do
      post :update_all, on: :collection
    end
    resources :learning_experiences, controller: 'users/learning_experiences', only: [:index, :show]
    resources :expectations, controller: 'users/expectations' do
      resources :expectation_statuses do
        post :publish, on: :member
        post :mark_as_read, on: :member
      end
    end
    resources :taken_assessments do
      patch :submit, on: :member
      post :track, on: :member
    end
    resources :employments, except: [:index, :show]
    resource :employment_profile
    resources :job_activities
    resources :tracker_statuses
    resources :projects
    resources :epics, controller: 'user_epics' do
      post :add_to_tracker, on: :member
    end
    resources :submitted_exercises, only: [] do
      get :generate_dot_file, on: :collection
    end
    get "/student_dashboard", to: "instructor/student_dashboard#show", on: :member
  end

  resources :epics do
    resources :cohorts, controller: 'cohort_epics'
  end

  resources :class_projects do
    resources :epics do
      resources :stories do
        post :reorder, on: :collection
      end
      post :reorder, on: :collection
    end
  end

  resources :learning_experiences, only: [] do
    resources :zpd_responses, only: [:new, :create, :index], controller: "learning_experiences/zpd_responses"
  end

  resources :writeups, only: [] do
    resources :comments, controller: 'writeup_comments'
  end

  resources :cohorts do
    resources :performances do
      get :data, on: :collection
    end
    resources :pair_rotations do
      post :generate, on: :collection
      post :assign, on: :member
      post :unassign, on: :member
      get :random, on: :collection
    end
    resources :given_assessments do
      get 'score/:question_id', action: 'score', as: :score
      post 'score/:question_id', action: 'submit_scores'
      post :pull_changes, on: :member
    end
    get :one_on_ones, :on => :member
    post :send_one_on_ones, on: :member
    get :acceptance, :on => :member
    post :refresh_acceptance, :on => :member
    get :mentorships, :on => :member
    get :social, :on => :member
    get "/student_dashboard", to: "student/student_dashboard#index"

    resource :student_dashboard, only: [:index] do
      get "js_challenges", to: "student/student_dashboard#js_challenges"
    end

    get "/info" => "student/info#index", :as => "info"
    get "/prereqs" => "student/info#prereqs", :as => "prereqs"

    resources :applications, only: [:index], controller: 'greenhouse_applications' do
      post :refresh, on: :collection
      post :import, on: :member
    end
    resources :writeups, controller: 'student/writeups', only: :index
    resources :writeup_topics, only: [] do
      resources :writeups, only: [:new, :create, :edit, :update, :destroy], controller: 'student/writeups'
    end
    resources :pairings, controller: 'student/pairings'
    resources :students, :only => [:index, :show], controller: 'student/students' do
      resources :mentorships
    end
    resources :exercises, :only => [:index, :show], controller: 'student/exercises' do
      resources :submissions, :only => [:new, :create, :edit, :update], controller: 'student/submissions'
    end
    resources :action_plan_entries, controller: 'student/action_plan_entries', only: :index
    resources :daily_plans do
      get :today, on: :collection
      get :search, on: :collection
    end

    resources :staffings, except: [:show] do
      post :add_as_owner, on: :member
    end
    resources :imports, only: [:index, :create]

    resources :student_deadlines, controller: 'student/student_deadlines', only: [:index, :edit, :update]
    resources :assignment_submissions, controller: 'student/assignment_submissions', only: [:index, :edit, :update, :show]
    resources :zpd_responses, controller: 'student/zpd_responses', except: [:destroy]
    resources :student_challenges, controller: 'student/student_challenges'
    resources :student_snippets, controller: 'student/student_snippets', only: [:index, :create, :show, :update]
  end

  namespace :instructor do
    resources :cohorts, only: [] do
      resources :writeup_topics do
        resources :writeups
      end
      resources :tracker_accounts do
        delete :destroy, on: :collection
      end
      resources :students, :only => [] do
        resources :action_plan_entries
      end
      resources :projects, only: :index
      resources :action_plans, only: :index
      resources :cohort_exercises
      resources :deadlines do
        resources :student_deadlines, only: [:index]
      end
      resources :assignments
      resources :assignment_submissions, only: [] do
        patch :toggle, on: :member
      end
      resources :challenges, only: [:new, :create, :index, :show]
      resources :zpd_responses, only: [:index]
      resources :assignment_submissions, only: [] do
        resources :assignment_submission_notes, except: [:index]
      end
      resources :snippets, only: [:index, :new, :create, :show] do
        resources :student_snippets, only: [:show]
      end
    end
  end
end

app/models/pair_rotation.rb
class PairRotation < ActiveRecord::Base
  belongs_to :cohort
  validates :cohort, presence: true

  validates :happened_on, uniqueness: {scope: :cohort, allow_blank: true}
  validates :position, uniqueness: {scope: :cohort}

  before_validation on: :create do
    if cohort && !position
      max_position = self.class.ordered.where(cohort_id: cohort).last.try(:position) || 0
      self.position = max_position + 1
    end
  end

  scope :ordered, ->{ order(:position) }

  def self.for_cohort(cohort)
    where(cohort_id: cohort)
  end

  def self.generate(cohort)
    rotations = round_robin(User.for_cohort(cohort).sort_by(&:full_name).map(&:id))
    position = where(cohort_id: cohort).maximum(:position) || 0
    transaction do
      rotations.each.with_index(position + 1) do |rotation, index|
        create!(
          cohort: cohort,
          pairs: rotation,
          position: index,
        )
      end
    end
  end

  #http://en.wikipedia.org/wiki/Round-robin_tournament#Scheduling_algorithm
  def self.round_robin(ids)
    ids = ids + [nil] if ids.length.odd?
    h = ids.length / 2
    a,b = ids.each_slice(h).to_a
    first, *rest = a + b.reverse

    (ids.length - 1).times.map do |i|
      x = rest[0..h - 2]
      y = rest[h - 1..-1]
      x.unshift(y.shift)
      y << x.pop
      rest = x + y
      ([first] + x).zip(y)
    end
  end

end

app/controllers/pair_rotations_controller.rb
class PairRotationsController < ApplicationController

  def index
    authorize(PairRotation)
    pair_rotations = PairRotation.for_cohort(@cohort).order(:position).to_a
    @todays_rotation = pair_rotations.find do |rotation|
      rotation.happened_on == Date.current
    end
    pair_rotations.delete(@todays_rotation)
    @assigned, @available = pair_rotations.partition do |rotation|
      rotation.happened_on
    end
    @users = User.for_cohort(@cohort).index_by(&:id)
  end

  def show
    @pair_rotation = PairRotation.find(params[:id])
    @users = User.for_cohort(@cohort).index_by(&:id)
    authorize(@pair_rotation)
  end

  def new
    @users = User.for_cohort(@cohort)
    @pair_rotation = PairRotation.new
    authorize(@pair_rotation)
  end

  def create
    pairs = params[:pairs].values.map{|pair|
      pair.map { |id| id.present? ? id.to_i : nil }
    }

    pair_rotation = PairRotation.new(
      cohort: @cohort,
      pairs: pairs,
    )
    authorize(pair_rotation)
    pair_rotation.save!
    redirect_to(
      cohort_pair_rotation_path(@cohort, pair_rotation),
      notice: "Pair rotation was created successfully"
    )
  end

  def random
    @users = User.for_cohort(@cohort)
    @pair_generator = PairGenerator.new(@users)
    @pairs = @pair_generator.random_pairs
  end

  def assign
    @pair_rotation = PairRotation.find(params[:id])
    authorize(@pair_rotation)
    if @pair_rotation.update(happened_on: Date.current)
      flash[:notice] = 'Rotation was assigned'
    else
      flash[:alert] = @pair_rotation.errors.full_messages.join(", ")
    end
    redirect_to cohort_pair_rotations_path(@cohort)
  end

  def unassign
    @pair_rotation = PairRotation.find(params[:id])
    authorize(@pair_rotation)
    @pair_rotation.update(happened_on: nil)
    flash[:notice] = 'Rotation was unassigned'
    redirect_to cohort_pair_rotations_path(@cohort)
  end

  def generate
    authorize(PairRotation)
    PairRotation.generate(@cohort)
    redirect_to cohort_pair_rotations_path(@cohort), notice: 'Rotations were generated'
  end

  def destroy
    @pair_rotation = PairRotation.find(params[:id])
    authorize(@pair_rotation)
    @pair_rotation.destroy
    redirect_to cohort_pair_rotations_path(@cohort), notice: 'Rotation was deleted'
  end
  end

app/views/pair_rotations/index.html.haml
.page-header
  .pull-right
    = link_to "New Rotation", new_cohort_pair_rotation_path(@cohort), class: "btn btn-info"
    = link_to "Generate", generate_cohort_pair_rotations_path(@cohort), method: :post, class: "btn btn-primary"
  %h1 Pair Rotations

- if @todays_rotation
  .page-header
    .pull-right
      = link_to "Unassign", unassign_cohort_pair_rotation_path(@cohort, @todays_rotation), class: "btn btn-info", method: :post

    %h2
      Today's Pairs
      (rotation #{link_to "##{@todays_rotation.position}", cohort_pair_rotation_path(@cohort, @todays_rotation)})

  %table.table
    %thead
      %tr
        %th A
        %th B
    %tbody
      - @todays_rotation.pairs.each do |pair|
        %tr
          - a, b = @users[pair.first], @users[pair.last]
          %td= a ? a.full_name : 'Instructor'
          %td= b ? b.full_name : 'Instructor'

%h2 Available

%table.table
  %thead
    %tr
      %th Position
      %th
  %tbody
    - @available.each do |rotation|
      %tr
        %td= link_to rotation.position, cohort_pair_rotation_path(@cohort, rotation)
        %td.text-right
          - if rotation == @available.first
            = link_to 'Assign', assign_cohort_pair_rotation_path(@cohort, rotation), method: :post, class: "btn btn-primary btn-sm"

%h2 Previously Assigned

%table.table
  %thead
    %tr
      %th Position
      %th Happened on
  %tbody
    - @assigned.each do |rotation|
      %tr
        %td= link_to rotation.position, cohort_pair_rotation_path(@cohort, rotation)
        %td= rotation.happened_on.strftime('%-m/%-d/%Y')

app/views/pair_rotations/new.html.haml
.page-header
  %h1 New Pair Rotation for #{@cohort.name}

= form_for [@cohort, @pair_rotation], html: {class: "form-horizontal"} do |f|
  = errors_for(f)

  .form-group
    .col-md-6.col-md-offset-2
      - @users.each do |user|
        .checkbox
          %label
            %input{type: :checkbox, data: {user_id: user.id, full_name: user.full_name, behavior: 'select-user'}}
            = user.full_name
      - if @users.length.odd?
        .checkbox
          %label
            %input{type: :checkbox, data: {user_id: nil, full_name: 'Instructor', behavior: 'select-user'}}
            Instructor

      %button(data-behavior="pair-users" class="btn btn-default") Pair Users

  .form-group
    .col-md-offset-2.col-md-4
      = f.submit class: 'btn btn-primary'
      - path = cohort_pair_rotations_path(@cohort)
      = link_to "cancel", path, class: "btn btn-default"

  .form-group
    .col-md-offset-2.col-md-4
      %table.table
        %thead
          %tr
            %th Pair One
            %th Pair Two
        %tbody(data-placeholder='pairs')

- content_for :javascripts do
  :javascript
    PairRotation.init();

app/views/pair_rotations/random.html.haml
.page-header
  .pull-right
    = link_to "Random", nil, class: "btn btn-info"

  %h1= @cohort.name

%table.table
  %thead
    %tr
      %th Pair 1
      %th Pair 2
  %tbody
    - @pairs.each do |pair|
      %tr
        %td= pair.first.full_name
        - if pair.second
          %td= pair.second.full_name
        - else
          %td.not-paired Instructor

app/views/pair_rotations/show.html.haml
.page-header
  .pull-right
    - if @pair_rotation.happened_on
      %p.lead Assigned on #{@pair_rotation.happened_on.strftime('%-m/%-d/%Y')}
    - else
      = link_to "Assign", assign_cohort_pair_rotation_path(@cohort, @pair_rotation), method: :post, class: "btn btn-primary"

  %h1
    Pair Rotation #{@pair_rotation.position} for #{@cohort.name}

%ol.breadcrumb
  %li= link_to 'Pair Rotations', cohort_pair_rotations_path(@cohort)
  %li.active= @pair_rotation.position

%table.table
  %thead
    %tr
      %th A
      %th B
  %tbody
    - @pair_rotation.pairs.each do |pair|
      %tr
        - a, b = @users[pair.first], @users[pair.last]
        %td= a ? a.full_name : 'Instructor'
        %td= b ? b.full_name : 'Instructor'

.row
  .col-md-12
    .well.text-center
      = link_to "Unassign", unassign_cohort_pair_rotation_path(@cohort, @pair_rotation), class: "btn btn-info", method: :post
      = link_to "Delete",
                cohort_pair_rotation_path(@cohort, @pair_rotation),
                method: :delete,
                class: "btn btn-danger",
                data: {confirm: "Are you sure?"}