config/routes.rb
Students::Application.routes.draw do

  root :to => "public#index"
  # new pages, behind a feature flag
  get 'new-root' => redirect('/')
  get 'people/:id' => "public#show", as: :public_student

  get 'signin' => "sessions#new", as: :signin
  post 'signin' => "sessions#sign_in_with_password"
  get 'set_password/:verifier' => "sessions#set_password", as: :set_password
  post 'set_password/:verifier' => "sessions#update_password"

  get "/preparation" => "public_pages#preparation_index", :as => "preparations"
  get "/preparation/:id" => "public_pages#preparation", :as => "preparation"
  get "/calendar" => "public_pages#calendar", :as => "calendar"
  resources :showcases
  resources :students, :only => :show

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure"
  get "/logout" => "sessions#destroy", :as => "logout"

  get "/mentors/:user_id" => "mentors#show", :as => :mentor

  resources :timelines, only: :index
  resources :campuses
  resources :courses do
    post :clone, on: :member
    resources :expectations
  end
  resources :job_activities, only: [] do
    get :all, on: :collection
  end
  resources :assessments
  resources :given_assessments, only: :create
  resources :enrollments
  resources :videos, only: :index

  resources :curriculums, only: [] do
    resources :learning_experiences do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
      get :assign, on: :collection
      post :assign, on: :member, action: :create_assignment
    end
    resources :exercises
  end

  resources :curriculums, module: :instructor do
    get :new_import, on: :member
    post :import, on: :member
    get :progress, on: :member
    get :activity, on: :member
    resources :standards, only: [:index, :new, :create] do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
    resources :subjects do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
  end
  resources :standards, module: :instructor do
    post :merge_objectives, on: :member
    get :delete, on: :member
    resources :objectives, only: [:new, :create] do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
  end
  resources :objectives, module: :instructor do
    get :delete, on: :member
  end

  namespace :api do
    get 'me' => 'base#me'
    post '/apps/:app_name/authenticate' => 'apps#authenticate'
    get 'sign-in' => 'auth#sign_in'
    resources :cohort_exercises, only: [] do
      resources :submissions, only: :index
    end
    resources :class_projects, only: :index
    resources :students, only: :index
    resources :student_projects, only: :index
    resources :stories
    resources :cohorts, only: :index do
      get :current, on: :collection
      resources :students, only: :index
    end
    get '/autograder/:cohort_id' => 'autograder#show'
  end

  get '/redirects/learning_experiences/:id' => 'redirects#learning_experience'

  resources :users do
    resources :performances, controller: 'users/performances' do
      post :update_all, on: :collection
    end
    resources :learning_experiences, controller: 'users/learning_experiences', only: [:index, :show]
    resources :expectations, controller: 'users/expectations' do
      resources :expectation_statuses do
        post :publish, on: :member
        post :mark_as_read, on: :member
      end
    end
    resources :taken_assessments do
      patch :submit, on: :member
      post :track, on: :member
    end
    resources :employments, except: [:index, :show]
    resource :employment_profile
    resources :job_activities
    resources :tracker_statuses
    resources :projects
    resources :epics, controller: 'user_epics' do
      post :add_to_tracker, on: :member
    end
    resources :submitted_exercises, only: [] do
      get :generate_dot_file, on: :collection
    end
    get "/student_dashboard", to: "instructor/student_dashboard#show", on: :member
  end

  resources :epics do
    resources :cohorts, controller: 'cohort_epics'
  end

  resources :class_projects do
    resources :epics do
      resources :stories do
        post :reorder, on: :collection
      end
      post :reorder, on: :collection
    end
  end

  resources :learning_experiences, only: [] do
    resources :zpd_responses, only: [:new, :create, :index], controller: "learning_experiences/zpd_responses"
  end

  resources :writeups, only: [] do
    resources :comments, controller: 'writeup_comments'
  end

  resources :cohorts do
    resources :performances do
      get :data, on: :collection
    end
    resources :pair_rotations do
      post :generate, on: :collection
      post :assign, on: :member
      post :unassign, on: :member
      get :random, on: :collection
    end
    resources :given_assessments do
      get 'score/:question_id', action: 'score', as: :score
      post 'score/:question_id', action: 'submit_scores'
      post :pull_changes, on: :member
    end
    get :one_on_ones, :on => :member
    post :send_one_on_ones, on: :member
    get :acceptance, :on => :member
    post :refresh_acceptance, :on => :member
    get :mentorships, :on => :member
    get :social, :on => :member
    get "/student_dashboard", to: "student/student_dashboard#index"

    resource :student_dashboard, only: [:index] do
      get "js_challenges", to: "student/student_dashboard#js_challenges"
    end

    get "/info" => "student/info#index", :as => "info"
    get "/prereqs" => "student/info#prereqs", :as => "prereqs"

    resources :applications, only: [:index], controller: 'greenhouse_applications' do
      post :refresh, on: :collection
      post :import, on: :member
    end
    resources :writeups, controller: 'student/writeups', only: :index
    resources :writeup_topics, only: [] do
      resources :writeups, only: [:new, :create, :edit, :update, :destroy], controller: 'student/writeups'
    end
    resources :pairings, controller: 'student/pairings'
    resources :students, :only => [:index, :show], controller: 'student/students' do
      resources :mentorships
    end
    resources :exercises, :only => [:index, :show], controller: 'student/exercises' do
      resources :submissions, :only => [:new, :create, :edit, :update], controller: 'student/submissions'
    end
    resources :action_plan_entries, controller: 'student/action_plan_entries', only: :index
    resources :daily_plans do
      get :today, on: :collection
      get :search, on: :collection
    end

    resources :staffings, except: [:show] do
      post :add_as_owner, on: :member
    end
    resources :imports, only: [:index, :create]

    resources :student_deadlines, controller: 'student/student_deadlines', only: [:index, :edit, :update]
    resources :assignment_submissions, controller: 'student/assignment_submissions', only: [:index, :edit, :update, :show]
    resources :zpd_responses, controller: 'student/zpd_responses', except: [:destroy]
    resources :student_challenges, controller: 'student/student_challenges'
    resources :student_snippets, controller: 'student/student_snippets', only: [:index, :create, :show, :update]
  end

  namespace :instructor do
    resources :cohorts, only: [] do
      resources :writeup_topics do
        resources :writeups
      end
      resources :tracker_accounts do
        delete :destroy, on: :collection
      end
      resources :students, :only => [] do
        resources :action_plan_entries
      end
      resources :projects, only: :index
      resources :action_plans, only: :index
      resources :cohort_exercises
      resources :deadlines do
        resources :student_deadlines, only: [:index]
      end
      resources :assignments
      resources :assignment_submissions, only: [] do
        patch :toggle, on: :member
      end
      resources :challenges, only: [:new, :create, :index, :show]
      resources :zpd_responses, only: [:index]
      resources :assignment_submissions, only: [] do
        resources :assignment_submission_notes, except: [:index]
      end
      resources :snippets, only: [:index, :new, :create, :show] do
        resources :student_snippets, only: [:show]
      end
    end
  end
end

app/controllers/instructor/action_plan_entries_controller.rb
class Instructor::ActionPlanEntriesController < InstructorRequiredController

  before_action do
    @user = User.for_cohort(@cohort).find(params[:student_id])
    if @cohort.curriculum_id
      @learning_experiences = LearningExperience.where(curriculum_id: @cohort.curriculum_id).ordered
    end
  end

  def index
    @entries = ActionPlanEntry.for_cohort_and_user(@cohort, @user).order('created_at desc')
  end

  def new
    @entry = ActionPlanEntry.new
  end

  def create
    @entry = ActionPlanEntry.new(entry_params)
    @entry.user = @user
    @entry.cohort = @cohort

    if @entry.save
      StudentMailer.action_plan_entry(current_user, @entry).deliver
      redirect_to(
        instructor_cohort_student_action_plan_entries_path(@cohort, @user),
        notice: 'Entry created successfully'
      )
    else
      render :new
    end
  end

  def edit
    @entry = ActionPlanEntry.for_cohort_and_user(@cohort, @user).find(params[:id])
  end

  def update
    @entry = ActionPlanEntry.for_cohort_and_user(@cohort, @user).find(params[:id])

    if @entry.update(entry_params)
      StudentMailer.action_plan_entry(current_user, @entry).deliver
      redirect_to(
        instructor_cohort_student_action_plan_entries_path(@cohort, @user),
        notice: 'Entry updated successfully'
      )
    else
      render :edit
    end
  end

  def destroy
    @entry = ActionPlanEntry.for_cohort_and_user(@cohort, @user)
      .find_by_id(params[:id])
      .try(:destroy)

    redirect_to(
      instructor_cohort_student_action_plan_entries_path(@cohort, @user),
      notice: 'Entry deleted successfully'
    )
  end

  private

  def entry_params
    params.require(:action_plan_entry).permit(
      :description,
      :learning_experience_id,
      :status,
      :due_on,
      :completed_on,
      :started_on,
    )
  end

end

app/controllers/instructor/action_plans_controller.rb
class Instructor::ActionPlansController < InstructorRequiredController

  def index
    @students = User.for_cohort(@cohort)
  end

end

app/controllers/instructor/assignment_submission_notes_controller.rb
class Instructor::AssignmentSubmissionNotesController < InstructorRequiredController
  def new
    @assignment_submission = AssignmentSubmission.find(params[:assignment_submission_id])
    @assignment_submission_note = AssignmentSubmissionNote.new
    @assignment_submission_notes = AssignmentSubmissionNote.where(assignment_submission_id: @assignment_submission.id)
  end

  def create
    @assignment_submission = AssignmentSubmission.find(params[:assignment_submission_id])
    @assignment_submission_note = AssignmentSubmissionNote.new(assignment_submission_note_params.merge(assignment_submission_id: params[:assignment_submission_id]))
    if @assignment_submission_note.save
      redirect_to instructor_cohort_assignment_path(@cohort.id, @assignment_submission.assignment.id), notice: "Note successfully added"
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def edit
    @assignment_submission = AssignmentSubmission.find(params[:assignment_submission_id])
    @assignment_submission_note = AssignmentSubmissionNote.find(params[:id])
  end

  def update
    @assignment_submission = AssignmentSubmission.find(params[:assignment_submission_id])
    @assignment_submission_note = AssignmentSubmissionNote.find(params[:id])
    if @assignment_submission_note.update(assignment_submission_note_params)
      redirect_to instructor_cohort_assignment_path(@cohort.id, @assignment_submission.assignment.id), notice: "Note successfully updated"
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def destroy
    AssignmentSubmissionNote.find(params[:id]).destroy
    @assignment_submission = AssignmentSubmission.find(params[:assignment_submission_id])
    redirect_to instructor_cohort_assignment_path(@cohort.id, @assignment_submission.assignment.id), notice: "Note destroyed"
  end

  private

  def assignment_submission_note_params
    params.require(:assignment_submission_note).permit(:content)
  end
end

app/controllers/instructor/assignment_submissions_controller.rb
class Instructor::AssignmentSubmissionsController < InstructorRequiredController
  def toggle
    assignment_submission = AssignmentSubmission.find(params[:id])
    assignment_submission.toggle!(:complete)
    redirect_to instructor_cohort_assignment_path(@cohort, assignment_submission.assignment.id)
  end
end

app/controllers/instructor/assignments_controller.rb
class Instructor::AssignmentsController < InstructorRequiredController

  include AssignmentsHelper

  def index
    @assignments = Assignment.where(cohort_id: params[:cohort_id]).order(:due_date)
  end

  def new
    @assignment = Assignment.new
  end

  def create
    @assignment = Assignment.new(assignment_params.merge(cohort_id: params[:cohort_id]))
    if @assignment.save
      AssignmentSubmission.seed_for_assignment(@assignment, @cohort)
      redirect_to instructor_cohort_assignments_path, notice: "Assignment Successfully Created"
    else
      render :new
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
  end

  def show
    @assignment = Assignment.find(params[:id])
    assignment_submissions = @assignment.assignment_submissions
    @submitted_assignment_submissions = assignment_submissions.select { |assignment_submission| assignment_submission.submitted && !assignment_submission.complete}
    @unsubmitted_assignment_submissions = assignment_submissions.select { |assignment_submission| !assignment_submission.submitted}
    @completed_assignment_submissions = assignment_submissions.select { |assignment_submission| assignment_submission.complete}
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update(assignment_params)
      redirect_to instructor_cohort_assignments_path, notice: "Assignment Successfully Updated"
    else
      render :edit
    end
  end

  def destroy
    Assignment.find(params[:id]).destroy
    redirect_to instructor_cohort_assignments_path, notice: "Assignment Destroyed"
  end

  private

  def assignment_params
    params.require(:assignment).permit(:name, :url, :due_date)
  end
end

app/controllers/instructor/challenges_controller.rb
class Instructor::ChallengesController < InstructorRequiredController
  def index
    @challenges = Challenge.where(cohort_id: @cohort.id)
  end

  def new
    @challenge = Challenge.new
  end

  def create
    @challenge = Challenge.new(challenge_params.merge(cohort_id: @cohort.id))
    if @challenge.save
      flash[:notice] = "Challenge Successfully Saved"
      redirect_to instructor_cohort_challenges_path(@cohort)
    else
      flash[:alert] = "Challenge could not be created"
      render :new
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
    student_challenges = StudentChallenge.where(challenge_id: @challenge.id)
    @user_student_challenges_presenters = UserStudentChallengesPresenter.build_from_student_challenges(student_challenges)
    @completed_users = @user_student_challenges_presenters.select { |user_student_challenge_presenter| user_student_challenge_presenter.complete }.map(&:user)
    @students = User.for_cohort(@cohort)
    @incompleted_users = @students - @completed_users
  end

  private

  def challenge_params
    params.require(:challenge).permit(:directory_name, :github_url)
  end
end

app/controllers/instructor/cohort_exercises_controller.rb
class Instructor::CohortExercisesController < InstructorRequiredController

  def index
    @cohort_exercises = @cohort.cohort_exercises.order(:created_at)
  end

  def show
    @exercise = CohortExercise.includes(:exercise).find(params[:id])
    @submissions = @exercise.submissions
    @students_missing_submission = @exercise.students_missing_submission
  end

  def new
    already_assigned_exercises = @cohort.exercises
    @exercises = Exercise.all.order(:name) - already_assigned_exercises
  end

  def create
    @cohort_exercise = CohortExercise.new(create_params)

    @cohort_exercise.save!
    redirect_to instructor_cohort_cohort_exercises_path, :notice => 'Exercise successfully added to cohort'
  end

  def destroy
    CohortExercise.find(params[:id]).destroy
    flash[:notice] = "Exercise removed."
    redirect_to :action => :index
  end

  private

  def create_params
    params.require(:cohort_exercise).
      permit(:exercise_id).
      merge(:cohort_id => params[:cohort_id])
  end
end

app/controllers/instructor/projects_controller.rb
class Instructor::ProjectsController < InstructorRequiredController

  def index
    @projects = StudentProject.for_user(User.for_cohort(@cohort))
                  .sort_by{|project| project.user.full_name }
  end

end

app/controllers/instructor/snippets_controller.rb
class Instructor::SnippetsController < InstructorRequiredController
	def index
		@snippets = Snippet.where(cohort_id: @cohort.id)
	end

	def new
		@snippet = Snippet.new
	end

	def create
		@snippet = Snippet.new(snippet_params.merge(cohort_id: params[:cohort_id]))
		if @snippet.save
			redirect_to instructor_cohort_snippet_path(@cohort, @snippet), notice: "Snippet successfully created"
		else
			render :new
		end
	end

	def show
		@snippet = Snippet.find(params[:id])
		@student_snippets = StudentSnippet.where(snippet_id: @snippet.id)
	end

	private

	def snippet_params
		params.require(:snippet).permit(:name)
	end
end

app/views/instructor/objectives/_form.html.haml
.form-group
  .col-md-offset-1.col-md-10
    = errors_for(f)

- if f.object.id
  .form-group
    = f.label :standard_id, class: 'control-label col-md-1'
    .col-md-9
      = f.collection_select :standard_id, @curriculum.standards.sort_by(&:name), :id, :name, {}, class: 'form-control'

.form-group
  = f.label :name, class: 'control-label col-md-1'
  .col-md-9
    = f.text_field :name, class: 'form-control', autofocus: true
    %p.help-block
      Cannot start with unmeasurable verbs like #{Objective::UNMEASURABLE_VERBS.map{|w| "\"#{w}\"" }.to_sentence}

.form-group
  = f.label :description, class: 'control-label col-md-1'
  .col-md-9
    = f.text_area :description, class: 'form-control', rows: 3, data: {editor: 'markdown'}

.form-group
  = f.label :guiding_questions, class: 'control-label col-md-1'
  .col-md-9
    = f.text_area :guiding_questions, class: 'form-control', rows: 5, data: {editor: 'markdown'}

.form-group
  = f.label :resources, class: 'control-label col-md-1'
  .col-md-9
    = f.text_area :resources, class: 'form-control', rows: 12, data: {editor: 'markdown'}

.form-group
  = f.label :questions, class: 'control-label col-md-1'
  .col-md-9
    = f.fields_for :questions do |qf|
      .question-form
        .form-group
          = qf.label :question, class: 'control-label col-md-1'
          .col-md-9
            = qf.text_field :question, class: 'form-control'

        .form-group
          = qf.label :question_type, 'Type', class: 'control-label col-md-1'
          .col-md-9
            = qf.select :question_type, ['text', 'textarea'], {}, class: 'form-control'

        .form-group
          = qf.label :correct_answer, 'Answer', class: 'control-label col-md-1'
          .col-md-9
            = qf.text_field :correct_answer, class: 'form-control'
            %p.help-block
              Notes for instructor grading
.form-group
  .col-md-9.col-md-offset-1
    = f.button 'Add New Question', class: 'btn btn-primary add-new-question'

.form-group
  = f.label :instructor_notes, class: 'control-label col-md-1'
  .col-md-9
    = f.text_area :instructor_notes, class: 'form-control', rows: 12, data: {editor: 'markdown'}

.form-group
  .col-md-9.col-md-offset-1
    - if params[:cohort_id]
      = hidden_field_tag :cohort_id, params[:cohort_id]
    = hidden_field_tag :return_to, params[:return_to]
    = f.submit class: 'btn btn-primary'
    - if f.object.id
      = f.submit "Save and Next", class: 'btn btn-info'
    = link_to "cancel", standard_path(@standard), class: 'btn btn-default'

app/views/instructor/objectives/delete.html.haml
.page-header
  .pull-right
  %h1 Delete Objective

%br
- curriculum = @objective.standard.curriculum
%ol.breadcrumb
  %li= link_to_if policy(curriculum).create?, "Curriculums", curriculums_path
  %li
    - if policy(curriculum).edit?
      = link_to curriculum.name, curriculum_path(curriculum)
    - else
      = link_to curriculum.name, user_performances_path(current_user)
  %li= link_to @objective.standard.name, standard_path(@objective.standard)
  %li= link_to @objective.name, objective_path(@objective)
  %li.active Delete

.jumbotron
  %h3
    There are #{pluralize @performances.length, "performance"}.

  %p
    Are you sure you want to delete "#{@objective.name}"?

  %p
    You cannot undo this action.

  = form_for @objective, method: :delete do |f|
    %p.text-center
      = f.submit "Yes, Delete", class: "btn btn-lg btn-danger", data: {confirm: "Are you sure?"}

app/views/instructor/objectives/edit.html.haml
.page-header
  %h2 Edit Objective

%ol.breadcrumb
  %li= link_to "Curriculums", curriculums_path
  %li= link_to @curriculum.name, curriculum_path(@curriculum)
  %li= link_to @standard.name, standard_path(@standard)
  %li= link_to @objective.name_was, standard_path(@objective)
  %li.active Edit

= form_for @objective, html: {class: 'form-horizontal'} do |f|
  = render 'form', f: f

.row
  .col-md-11.col-md-offset-1
    %h2 Standard Resources
    %pre= @objective.standard.resources
    .well.text-center
      = link_to "Delete Objective", delete_objective_path(@objective), class: "btn btn-danger"

app/views/instructor/objectives/new.html.haml
.page-header
  %h2 New Objective

%ol.breadcrumb
  %li= link_to "Curriculums", curriculums_path
  %li= link_to @curriculum.name, curriculum_path(@curriculum)
  %li= link_to @standard.name, standard_path(@standard)
  %li.active New Objective

= form_for [@standard, @objective], html: {class: 'form-horizontal'} do |f|
  = render 'form', f: f

app/views/instructor/objectives/reorder.html.haml
.page-header
  %h1 Reorder Objectives

%ol.breadcrumb
  %li= link_to "Curriculums", curriculums_path
  %li= link_to @curriculum.name, curriculum_path(@curriculum)
  %li= link_to @standard.name, standard_path(@standard)
  %li.active Reorder

%table.table.table-striped{data: {behavior: :tablednd, reorder_url: reorder_standard_objectives_path(@standard)}}
  %thead
    %tr
      %th Objective
  %tbody
    - @objectives.each do |objective|
      %tr{id: objective.id}
        %td= link_to objective.name, objective_path(objective)

app/views/instructor/objectives/show.html.haml
.page-header
  .pull-right
    - if policy(@objective).edit?
      = link_to "Edit Objective", edit_objective_path(@objective), class: "btn btn-info"
  %h1 Objective

%br
- curriculum = @objective.standard.curriculum
%ol.breadcrumb
  %li= link_to_if policy(curriculum).create?, "Curriculums", curriculums_path
  %li
    - if policy(curriculum).edit?
      = link_to curriculum.name, curriculum_path(curriculum)
    - else
      = link_to curriculum.name, user_performances_path(current_user)
  %li= link_to @objective.standard.name, standard_path(@objective.standard)
  %li.active Objective

.row
  .col-md-6
    %h2
      Objective
      - if policy(@objective).edit?
        %small
          = link_to "(edit)", edit_objective_path(@objective)

    %p= @objective.name
    - if @objective.description?
      %blockquote= markdownify @objective.description

    - if @objective.guiding_questions?
      %h3 Guiding Questions
      = markdownify(@objective.guiding_questions)

    - if @objective.resources?
      %h3 Resources
      = markdownify(@objective.resources)

    - if policy(@objective).edit? && @objective.instructor_notes?
      %h3 Instructor Notes
      = markdownify(@objective.instructor_notes)

  .col-md-6
    %h2
      Standard
      - if policy(@objective.standard).edit?
        %small
          = link_to "(edit)", edit_standard_path(@objective.standard)

    %p= link_to @objective.standard.name, standard_path(@objective.standard)
    - if @objective.standard.description?
      %blockquote= markdownify @objective.standard.description

    - if @objective.standard.guiding_questions?
      %h3 Guiding Questions
      = markdownify(@objective.standard.guiding_questions)

    - if @objective.standard.resources
      %h3 Resources
      = markdownify(@objective.standard.resources)

    - if policy(@objective.standard).edit? && @objective.standard.instructor_notes?
      %h3 Instructor Notes
      = markdownify(@objective.standard.instructor_notes)

- if @learning_experiences.present?
  .page-header
    %h1 Learning Experiences
  - @learning_experiences.each do |experience|
    .panel.panel-default
      .panel-heading
        - if policy(experience).update?
          .pull-right
            = link_to "edit", edit_curriculum_learning_experience_path(@curriculum, experience)
        %h3.panel-title
          - if policy(experience).update?
            = link_to experience.name, edit_curriculum_learning_experience_path(@curriculum, experience)
          - else
            = link_to experience.name, user_learning_experience_path(current_user, experience)
      - if experience.description?
        .panel-body
          %blockquote= markdownify experience.description