config/routes.rb
Students::Application.routes.draw do

  root :to => "public#index"
  # new pages, behind a feature flag
  get 'new-root' => redirect('/')
  get 'people/:id' => "public#show", as: :public_student

  get 'signin' => "sessions#new", as: :signin
  post 'signin' => "sessions#sign_in_with_password"
  get 'set_password/:verifier' => "sessions#set_password", as: :set_password
  post 'set_password/:verifier' => "sessions#update_password"

  get "/preparation" => "public_pages#preparation_index", :as => "preparations"
  get "/preparation/:id" => "public_pages#preparation", :as => "preparation"
  get "/calendar" => "public_pages#calendar", :as => "calendar"
  resources :showcases
  resources :students, :only => :show

  get "/auth/:provider/callback" => "sessions#create"
  get "/auth/failure" => "sessions#failure"
  get "/logout" => "sessions#destroy", :as => "logout"

  get "/mentors/:user_id" => "mentors#show", :as => :mentor

  resources :timelines, only: :index
  resources :campuses
  resources :courses do
    post :clone, on: :member
    resources :expectations
  end
  resources :job_activities, only: [] do
    get :all, on: :collection
  end
  resources :assessments
  resources :given_assessments, only: :create
  resources :enrollments
  resources :videos, only: :index

  resources :curriculums, only: [] do
    resources :learning_experiences do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
      get :assign, on: :collection
      post :assign, on: :member, action: :create_assignment
    end
    resources :exercises
  end

  resources :curriculums, module: :instructor do
    get :new_import, on: :member
    post :import, on: :member
    get :progress, on: :member
    get :activity, on: :member
    resources :standards, only: [:index, :new, :create] do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
    resources :subjects do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
  end
  resources :standards, module: :instructor do
    post :merge_objectives, on: :member
    get :delete, on: :member
    resources :objectives, only: [:new, :create] do
      get :reorder, on: :collection
      post :reorder, on: :collection, action: :update_order
    end
  end
  resources :objectives, module: :instructor do
    get :delete, on: :member
  end

  namespace :api do
    get 'me' => 'base#me'
    post '/apps/:app_name/authenticate' => 'apps#authenticate'
    get 'sign-in' => 'auth#sign_in'
    resources :cohort_exercises, only: [] do
      resources :submissions, only: :index
    end
    resources :class_projects, only: :index
    resources :students, only: :index
    resources :student_projects, only: :index
    resources :stories
    resources :cohorts, only: :index do
      get :current, on: :collection
      resources :students, only: :index
    end
    get '/autograder/:cohort_id' => 'autograder#show'
  end

  get '/redirects/learning_experiences/:id' => 'redirects#learning_experience'

  resources :users do
    resources :performances, controller: 'users/performances' do
      post :update_all, on: :collection
    end
    resources :learning_experiences, controller: 'users/learning_experiences', only: [:index, :show]
    resources :expectations, controller: 'users/expectations' do
      resources :expectation_statuses do
        post :publish, on: :member
        post :mark_as_read, on: :member
      end
    end
    resources :taken_assessments do
      patch :submit, on: :member
      post :track, on: :member
    end
    resources :employments, except: [:index, :show]
    resource :employment_profile
    resources :job_activities
    resources :tracker_statuses
    resources :projects
    resources :epics, controller: 'user_epics' do
      post :add_to_tracker, on: :member
    end
    resources :submitted_exercises, only: [] do
      get :generate_dot_file, on: :collection
    end
    get "/student_dashboard", to: "instructor/student_dashboard#show", on: :member
  end

  resources :epics do
    resources :cohorts, controller: 'cohort_epics'
  end

  resources :class_projects do
    resources :epics do
      resources :stories do
        post :reorder, on: :collection
      end
      post :reorder, on: :collection
    end
  end

  resources :learning_experiences, only: [] do
    resources :zpd_responses, only: [:new, :create, :index], controller: "learning_experiences/zpd_responses"
  end

  resources :writeups, only: [] do
    resources :comments, controller: 'writeup_comments'
  end

  resources :cohorts do
    resources :performances do
      get :data, on: :collection
    end
    resources :pair_rotations do
      post :generate, on: :collection
      post :assign, on: :member
      post :unassign, on: :member
      get :random, on: :collection
    end
    resources :given_assessments do
      get 'score/:question_id', action: 'score', as: :score
      post 'score/:question_id', action: 'submit_scores'
      post :pull_changes, on: :member
    end
    get :one_on_ones, :on => :member
    post :send_one_on_ones, on: :member
    get :acceptance, :on => :member
    post :refresh_acceptance, :on => :member
    get :mentorships, :on => :member
    get :social, :on => :member
    get "/student_dashboard", to: "student/student_dashboard#index"

    resource :student_dashboard, only: [:index] do
      get "js_challenges", to: "student/student_dashboard#js_challenges"
    end

    get "/info" => "student/info#index", :as => "info"
    get "/prereqs" => "student/info#prereqs", :as => "prereqs"

    resources :applications, only: [:index], controller: 'greenhouse_applications' do
      post :refresh, on: :collection
      post :import, on: :member
    end
    resources :writeups, controller: 'student/writeups', only: :index
    resources :writeup_topics, only: [] do
      resources :writeups, only: [:new, :create, :edit, :update, :destroy], controller: 'student/writeups'
    end
    resources :pairings, controller: 'student/pairings'
    resources :students, :only => [:index, :show], controller: 'student/students' do
      resources :mentorships
    end
    resources :exercises, :only => [:index, :show], controller: 'student/exercises' do
      resources :submissions, :only => [:new, :create, :edit, :update], controller: 'student/submissions'
    end
    resources :action_plan_entries, controller: 'student/action_plan_entries', only: :index
    resources :daily_plans do
      get :today, on: :collection
      get :search, on: :collection
    end

    resources :staffings, except: [:show] do
      post :add_as_owner, on: :member
    end
    resources :imports, only: [:index, :create]

    resources :student_deadlines, controller: 'student/student_deadlines', only: [:index, :edit, :update]
    resources :assignment_submissions, controller: 'student/assignment_submissions', only: [:index, :edit, :update, :show]
    resources :zpd_responses, controller: 'student/zpd_responses', except: [:destroy]
    resources :student_challenges, controller: 'student/student_challenges'
    resources :student_snippets, controller: 'student/student_snippets', only: [:index, :create, :show, :update]
  end

  namespace :instructor do
    resources :cohorts, only: [] do
      resources :writeup_topics do
        resources :writeups
      end
      resources :tracker_accounts do
        delete :destroy, on: :collection
      end
      resources :students, :only => [] do
        resources :action_plan_entries
      end
      resources :projects, only: :index
      resources :action_plans, only: :index
      resources :cohort_exercises
      resources :deadlines do
        resources :student_deadlines, only: [:index]
      end
      resources :assignments
      resources :assignment_submissions, only: [] do
        patch :toggle, on: :member
      end
      resources :challenges, only: [:new, :create, :index, :show]
      resources :zpd_responses, only: [:index]
      resources :assignment_submissions, only: [] do
        resources :assignment_submission_notes, except: [:index]
      end
      resources :snippets, only: [:index, :new, :create, :show] do
        resources :student_snippets, only: [:show]
      end
    end
  end
end

app/models/epic.rb
class Epic < ActiveRecord::Base

  enum category: [:mvp, :stretch]

  belongs_to :class_project
  has_many :stories, :dependent => :destroy
  has_many :student_stories, :dependent => :destroy
  has_many :cohort_epics, :dependent => :destroy

  validates :class_project, presence: true
  validates :name,
            presence: true,
            uniqueness: {scope: [:class_project_id, :category], case_sensitive: false}
  validates :position,
            presence: true,
            numericality: true,
            uniqueness: {scope: :class_project_id}

  before_validation on: :create do
    if class_project && !position
      max_position = self.class.ordered.where(class_project_id: class_project).last.try(:position) || 0
      self.position = max_position + 1
    end
  end

  def self.ordered
    order(:position)
  end

end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController

  before_action do
    @class_project = ClassProject.find(params[:class_project_id])
  end

  def index
    @epics = @class_project.epics.ordered
  end

  include Reorderable
  def reorder
    update_positions Epic.ordered.where(class_project_id: @class_project)
  end

  def new
    @epic = Epic.new
  end

  def create
    @epic = Epic.new(epic_params)
    @epic.class_project = @class_project

    if @epic.save
      redirect_to(
        class_project_epic_path(@class_project, @epic),
        notice: 'Epic was added successfully'
      )
    else
      render :new
    end
  end

  def show
    @epic = @class_project.epics.find(params[:id])
    @story = Story.new
  end

  def edit
    @epic = @class_project.epics.find(params[:id])
  end

  def update
    @epic = @class_project.epics.find(params[:id])

    if @epic.update(epic_params)
      redirect_to(
        class_project_epic_path(@class_project, @epic),
        notice: 'Epic was updated successfully'
      )
    else
      render :edit
    end
  end

  def destroy
    @epic = @class_project.epics.find_by(id: params[:id])
    @epic.try(:destroy)
    redirect_to(
      class_project_epics_path(@class_project),
      notice: 'Epic removed successfully'
    )
  end

  private

  def epic_params
    params.require(:epic).permit(
      :class_project_id,
      :name,
      :category,
      :wireframes,
      :position,
      :label,
    )
  end
end

app/helpers/epics_helper.rb
module EpicsHelper

  def epic_markdown(epic)
    string = "### gCamp Stories: #{epic.name}".html_safe
    string << "\n\n```\n"
    string << ['Type', 'Estimate', 'Current State', 'Labels', 'Story', 'Description'].to_csv
    epic.stories.each do |story|
      string << ['feature', 1,'unstarted',[epic.label, epic.category].reject(&:blank?).join(", "), story.title, story.description].to_csv
    end
    string << "\n```\n\n"
    string << epic.wireframes
    string
  end

end

app/views/epics/_form.html.haml
= errors_for(f)
- rows = 12

.form-group
  = f.label :name, class: "col-sm-2 control-label"
  .col-sm-4
    = f.text_field :name, class: "form-control", autofocus: true

.form-group
  = f.label :category, class: "col-sm-2 control-label"
  .col-sm-4
    = f.collection_select :category, Epic.categories, :first, :first, {}, class: "form-control"

.form-group
  = f.label :label, class: "col-sm-2 control-label"
  .col-sm-10
    = f.text_field :label, class: "form-control"

.form-group
  = f.label :wireframes, class: "col-sm-2 control-label"
  .col-sm-10
    = f.text_area :wireframes, class: "form-control", rows: rows

.form-group
  .col-md-offset-2.col-md-4
    = f.submit class: 'btn btn-primary'
    - path = class_project_epics_path(@class_project)
    = link_to "cancel", path, class: "btn btn-default"

app/views/epics/edit.html.haml
.page-header
  %h1 Edit Epic

%ol.breadcrumb
  %li= link_to "Class Projects", class_projects_path
  %li= link_to "#{@class_project.name} Epics", class_project_epics_path(@class_project)
  %li.active Edit

- url = class_project_epic_path(@class_project, @epic)
= form_for @epic, url: url, html: {class: "form-horizontal"} do |f|
  = render 'form', f: f

app/views/epics/index.html.haml
.page-header
  .pull-right
    = link_to new_class_project_epic_path(@class_project), class: "btn btn-info" do
      %i.glyphicon.glyphicon-plus
      New Epic

  %h2 #{@class_project.name} Epics

%ol.breadcrumb
  %li= link_to "Class Projects", class_projects_path
  %li.active= "#{@class_project.name} Epics"

.row
  .col-md-12
    %table.table{data: {behavior: :tablednd, reorder_url: reorder_class_project_epics_path(@class_project)}}
      %thead
        %th Name
        %th Category
        %th Label
        %th
      %tbody
        - @epics.each do |epic|
          %tr{id: epic.id}
            %td= link_to epic.name, class_project_epic_path(@class_project, epic)
            %td= epic.category
            %td= epic.label
            %td
              .pull-right
                = link_to 'edit', edit_class_project_epic_path(@class_project, epic)

app/views/epics/new.html.haml
.page-header
  %h1 New Epic

- url = class_project_epics_path(@class_project)
= form_for @epic, url: url, html: {class: "form-horizontal"} do |f|
  = render 'form', f: f

app/views/epics/show.html.haml
.page-header
  .pull-right
    = link_to new_class_project_epic_path(@class_project), class: "btn btn-info" do
      %i.glyphicon.glyphicon-plus
      New Epic
    = link_to edit_class_project_epic_path(@class_project, @epic), class: "btn btn-info" do
      %i.glyphicon.glyphicon-pencil
      Edit

  %h1 #{@epic.name}

%ol.breadcrumb
  %li= link_to "Class Projects", class_projects_path
  %li= link_to "#{@class_project.name} Epics", class_project_epics_path(@class_project)
  %li.active= @epic.name

.panel.panel-default
  .panel-heading
    %h3.panel-title
      MVP Stories
  - if @epic.stories.present?
    %table.table.table-bordered{data: {behavior: :tablednd, reorder_url: reorder_class_project_epic_stories_path(@class_project, @epic)}}
      %thead
        %tr
          %th
          %th Title
          %th Description
      %tbody
        - @epic.stories.ordered.each do |story|
          %tr{id: story.id}
            %td(style="width: 1em;")
              - css_class = {'feature' => 'label label-info', 'bug' => 'label label-danger', 'chore' => 'label label-default'}
              %span{class: css_class[story.story_type], title: story.story_type}= story.story_type.first
            %td
              = link_to "#{story.title}", edit_class_project_epic_story_path(@class_project, @epic, story)
              - if story.slug?
                %br
                %small= story.slug
            %td= markdownify story.description
  .panel-body
    = render 'stories/form'

#cohort-assignments.panel.panel-default
  .panel-heading
    %h3.panel-title
      Cohort Assignments
  %table.table.table-bordered
    %thead
      %tr
        %th Cohort
        %th
    %tbody
      - cohort_epics = CohortEpic.where(epic_id: @epic).index_by(&:cohort_id)
      - Cohort.all.each do |cohort|
        %tr
          %td= link_to cohort.name, cohort_path(cohort)
          %td.text-right
            - if cohort_epic = cohort_epics[cohort.id]
              = link_to "Unassign",
                        epic_cohort_path(@epic, cohort_epic),
                        method: :delete,
                        data: {confirm: "Are you sure?"},
                        class: "btn btn-danger btn-sm"
            - else
              = link_to "Assign",
                        epic_cohorts_path(@epic, cohort_id: cohort.id),
                        method: :post,
                        class: "btn btn-primary btn-sm"

.panel.panel-default
  .panel-heading
    %h3.panel-title
      Wireframes
  .panel-body
    = markdownify(@epic.wireframes)

.panel.panel-default
  .panel-heading
    %h3.panel-title
      .pull-right
        = link_to "Copy to Clipboard", "#", data: {clipboard_text: epic_markdown(@epic), prevent_jump: true}
      Markdown for class notes
  .panel-body
    %pre
      = epic_markdown(@epic)